image: geerlingguy/drupal-vm
stages:
  - validate
  - build
  - test
  - deploy

variables:
  APP_NAME: joeyspaw 

before_script:
  - apt-get update
  - apt-get install unzip php7.1-bz2 -y
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install
  - php composer.phar run-script blt-alias
  - source ~/.bashrc

validate:
  stage: validate
  script:
    - echo "Validated!"
    - apt-get update
    - apt-get install unzip php7.1-bz2 -y
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install
    - php composer.phar run-script blt-alias
    - source ~/.bashrc

build:
  stage: build
  script:
    - composer validate --no-check-all --ansi
    - composer install --ansi
    - blt setup:build

test:
  stage: test
  script:
    - echo "testing skipped"

production:
  stage: deploy
  script:
    - git branch
    - git remote -v
    - blt deploy --commit-msg "$CI_COMMIT_SHA" --branch master --no-interaction
    - git remote -v
  environment:
    name: production
    url: http://$APP_NAME.stage.bsddigital.com
  only:
    - master
