project:
  machine_name: joeyspaw
  prefix: BLT
  human_name: 'BLTed 8'
  profile:
    name: standard
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes:
    acquia: 'joeyspaw@svn-634.devcloud.hosting.acquia.com:joeyspaw.git'
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector]
    uninstall: [devel, views_ui]
behat:
 null 
phpunit: 
 null
